stages:
  data_ingestion:
    cmd: python src/ChestCancerClassification/pipeline/data_ingestion_pipeline.py
    deps:
      - src/ChestCancerClassification/pipeline/data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest_CT_Scan_Data

  prepare_base_model:
    cmd: python src/ChestCancerClassification/pipeline/prepare_base_model_pipeline.py
    deps:
      - src/ChestCancerClassification/pipeline/prepare_base_model_pipeline.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/ChestCancerClassification/pipeline/model_trainer_pipeline.py
    deps:
      - src/ChestCancerClassification/pipeline/model_trainer_pipeline.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest_CT_Scan_data
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/ChestCancerClassification/pipeline/model_evaluation_pipeline.py
    deps:
      - src/ChestCancerClassification/pipeline/model_evaluation_pipeline.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest_CT_Scan_Data
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false
